[package]
name = "test_alloc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sysinfo = "0.28.3"
tokio = { version = "1.26.0", features = ["full"] }
rand = "0.8.5"